apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: 
    server: https://34.88.8.112
  name: 
contexts:
- context:
    cluster: 
    namespace: the-hole
    user: The Hole?
  name: The Hole?
current-context: The Hole?
users:
- name: The Hole?
  user:
    token: 
